name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 2.2.3
homepage: https://github.com/Hexer10/youtube_explode_dart

topics:
  - youtube
  - video
  - streams

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  html: ^0.15.5
  http: ^1.2.2
  http_parser: ^4.0.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  source_gen: ^1.5.0
  test: ^1.25.8

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/videos/video_controller.dart"
